[workspace]
members = [
    # "epha-ai",
    "epha-agent",
    "psyche/loom",
    "psyche/loom-client",

    "dialogue/atrium",
    "dialogue/atrium-client",
    "dialogue/atrium-cli"
]

resolver = "3"
