//! PublisherMessage - the message structure sent from Publishers
//!
//! This module defines the message format that Publishers send to subscribers.
//! The message contains a dual-timestamp design:
//! - `timestamp`: Message creation time (Publisher-side)
//! - When converted to MemoryFragment, a second timestamp is added (epha-ai side)

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use time::OffsetDateTime;

/// Priority levels for publisher messages
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum MessagePriority {
    /// Low priority - informational messages
    Low,
    /// Normal priority - default
    Normal,
    /// High priority - needs timely processing
    High,
    /// Urgent - requires immediate attention
    Urgent,
}

impl Default for MessagePriority {
    fn default() -> Self {
        Self::Normal
    }
}

impl std::fmt::Display for MessagePriority {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Low => write!(f, "low"),
            Self::Normal => write!(f, "normal"),
            Self::High => write!(f, "high"),
            Self::Urgent => write!(f, "urgent"),
        }
    }
}

/// Raw message sent from a Publisher
///
/// Dual timestamp design:
/// - `timestamp`: When message was created (Publisher-side)
/// - MemoryFragment.timestamp: When message entered context (epha-ai side, generated by .build())
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublisherMessage {
    /// Unique identifier of the Publisher
    pub publisher_id: String,

    /// Message type (e.g., chat_message, timer_trigger, system_notification)
    pub message_type: String,

    /// Message payload containing type-specific data
    pub payload: serde_json::Value,

    /// When the message was created (Publisher-side)
    #[serde(with = "time::serde::iso8601")]
    pub timestamp: OffsetDateTime,

    /// Message priority
    #[serde(default)]
    pub priority: MessagePriority,

    /// Additional metadata
    #[serde(default)]
    pub metadata: HashMap<String, String>,
}

impl PublisherMessage {
    /// Create a new PublisherMessage with the current timestamp
    pub fn new(
        publisher_id: impl Into<String>,
        message_type: impl Into<String>,
        payload: serde_json::Value,
    ) -> Self {
        Self {
            publisher_id: publisher_id.into(),
            message_type: message_type.into(),
            payload,
            timestamp: OffsetDateTime::now_utc(),
            priority: MessagePriority::Normal,
            metadata: HashMap::new(),
        }
    }

    /// Builder pattern: set the timestamp
    pub fn with_timestamp(mut self, timestamp: OffsetDateTime) -> Self {
        self.timestamp = timestamp;
        self
    }

    /// Builder pattern: set the priority
    pub fn with_priority(mut self, priority: MessagePriority) -> Self {
        self.priority = priority;
        self
    }

    /// Builder pattern: add metadata
    pub fn with_metadata(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.metadata.insert(key.into(), value.into());
        self
    }
}

/// Health status returned by Publisher health checks
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthStatus {
    /// Whether the publisher is healthy
    pub healthy: bool,

    /// Uptime in seconds
    pub uptime_seconds: u64,

    /// Total messages sent since start
    pub messages_sent: u64,

    /// When the last message was sent
    #[serde(with = "time::serde::iso8601::option")]
    pub last_message_at: Option<OffsetDateTime>,

    /// Optional additional info
    #[serde(default)]
    pub details: HashMap<String, String>,
}

impl HealthStatus {
    /// Create a healthy status
    pub fn healthy() -> Self {
        Self {
            healthy: true,
            uptime_seconds: 0,
            messages_sent: 0,
            last_message_at: None,
            details: HashMap::new(),
        }
    }

    /// Create an unhealthy status
    pub fn unhealthy(reason: impl Into<String>) -> Self {
        let mut details = HashMap::new();
        details.insert("reason".to_string(), reason.into());
        Self {
            healthy: false,
            uptime_seconds: 0,
            messages_sent: 0,
            last_message_at: None,
            details,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_message_creation() {
        let msg = PublisherMessage::new(
            "test-publisher",
            "test_type",
            json!({"key": "value"}),
        );

        assert_eq!(msg.publisher_id, "test-publisher");
        assert_eq!(msg.message_type, "test_type");
        assert_eq!(msg.priority, MessagePriority::Normal);
        assert!(msg.metadata.is_empty());
    }

    #[test]
    fn test_message_with_options() {
        let msg = PublisherMessage::new(
            "pub-1",
            "notification",
            json!({"text": "hello"}),
        )
        .with_priority(MessagePriority::High)
        .with_metadata("source", "telegram");

        assert_eq!(msg.priority, MessagePriority::High);
        assert_eq!(msg.metadata.get("source"), Some(&"telegram".to_string()));
    }

    #[test]
    fn test_message_serialization() {
        let msg = PublisherMessage::new(
            "timer-service",
            "timer_trigger",
            json!({"timer_id": "t1", "name": "test"}),
        );

        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"publisher_id\":\"timer-service\""));
        assert!(json.contains("\"message_type\":\"timer_trigger\""));
    }

    #[test]
    fn test_priority_display() {
        assert_eq!(format!("{}", MessagePriority::Low), "low");
        assert_eq!(format!("{}", MessagePriority::Normal), "normal");
        assert_eq!(format!("{}", MessagePriority::High), "high");
        assert_eq!(format!("{}", MessagePriority::Urgent), "urgent");
    }

    #[test]
    fn test_health_status() {
        let healthy = HealthStatus::healthy();
        assert!(healthy.healthy);

        let unhealthy = HealthStatus::unhealthy("Connection lost");
        assert!(!unhealthy.healthy);
        assert_eq!(
            unhealthy.details.get("reason"),
            Some(&"Connection lost".to_string())
        );
    }
}
