//! Publisher module - defines the Publisher trait and related types
//!
//! This module provides the abstractions for external data sources (Publishers)
//! that can send messages to the SubscriptionManager.
//!
//! # Architecture
//!
//! ```text
//! ┌──────────────────┐     ┌──────────────────┐     ┌──────────────────┐
//! │    Publisher     │     │    Publisher     │     │    Publisher     │
//! │  (Timer Service) │     │  (Telegram Bot)  │     │  (Email Gateway) │
//! └────────┬─────────┘     └────────┬─────────┘     └────────┬─────────┘
//!          │                        │                        │
//!          │   subscribe()          │   subscribe()          │   subscribe()
//!          │                        │                        │
//!          └────────────────────────┼────────────────────────┘
//!                                   │
//!                                   ▼
//!                    ┌─────────────────────────┐
//!                    │   SubscriptionManager   │
//!                    │       (Subscriber)      │
//!                    └─────────────────────────┘
//! ```
//!
//! # Key Concepts
//!
//! - **Publisher**: Trait for external data sources that produce messages
//! - **PublisherMessage**: The message format with Publisher-side timestamp
//! - **HealthStatus**: Health check response structure
//!
//! # Dual Timestamp Design
//!
//! PublisherMessage has a `timestamp` field generated by the Publisher.
//! When converted to MemoryFragment, a second timestamp is added by epha-ai.
//!
//! | Timestamp | Location | Generator | Purpose |
//! |-----------|----------|-----------|---------|
//! | `PublisherMessage.timestamp` | PublisherMessage | Publisher | When message occurred |
//! | `MemoryFragment.timestamp` | MemoryFragment | epha-ai | When entered context |

mod error;
mod message;
mod r#trait;

pub use error::PublisherError;
pub use message::{HealthStatus, MessagePriority, PublisherMessage};
pub use r#trait::Publisher;
