use super::types::{MemoryFragment, MemoryKind};
use time::OffsetDateTime;

/// Builder for creating MemoryFragment instances with flexible configuration
pub struct MemoryFragmentBuilder {
    fragment: MemoryFragment,
}

impl MemoryFragmentBuilder {
    /// Create a new builder with required fields
    ///
    /// # Arguments
    /// * `content` - The memory content as JSON string (required)
    /// * `kind` - The memory kind (required)
    pub fn new(content: String, kind: MemoryKind) -> Self {
        Self {
            fragment: MemoryFragment {
                id: 0, // Will be set by InfluxDB manager when inserted
                content,
                timestamp: OffsetDateTime::now_utc(),
                kind,
            },
        }
    }

    /// Set the id of the memory fragment
    ///
    /// Note: The id is typically auto-generated by the Snowflake ID generator.
    /// This method is particularly useful when constructing test data in unit tests.
    pub fn id(mut self, id: i64) -> Self {
        self.fragment.id = id;
        self
    }

    /// Set the content of the memory fragment
    pub fn content(mut self, content: String) -> Self {
        self.fragment.content = content;
        self
    }

    /// Set the timestamp
    pub fn timestamp(mut self, timestamp: OffsetDateTime) -> Self {
        self.fragment.timestamp = timestamp;
        self
    }

    /// Set the kind of the memory fragment
    pub fn kind(mut self, kind: MemoryKind) -> Self {
        self.fragment.kind = kind;
        self
    }

    /// Build the final MemoryFragment
    pub fn build(self) -> MemoryFragment {
        self.fragment
    }
}

impl Default for MemoryFragmentBuilder {
    fn default() -> Self {
        Self::new(String::new(), MemoryKind::Message)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_builder_basic_functionality() {
        let fragment = MemoryFragmentBuilder::new(
            r#"{"type":"test","text":"content"}"#.to_string(),
            MemoryKind::Message,
        )
        .build();

        assert_eq!(fragment.content, r#"{"type":"test","text":"content"}"#);
        assert_eq!(fragment.kind, MemoryKind::Message);
    }

    #[test]
    fn test_memory_kind_creation() {
        let thought_fragment =
            MemoryFragmentBuilder::new("thinking...".to_string(), MemoryKind::Thought).build();
        assert_eq!(thought_fragment.kind, MemoryKind::Thought);

        let action_fragment =
            MemoryFragmentBuilder::new("action...".to_string(), MemoryKind::Action).build();
        assert_eq!(action_fragment.kind, MemoryKind::Action);

        let message_fragment =
            MemoryFragmentBuilder::new("message...".to_string(), MemoryKind::Message).build();
        assert_eq!(message_fragment.kind, MemoryKind::Message);
    }

    #[test]
    fn test_memory_kind_from_str() {
        assert_eq!(MemoryKind::from_str("thought"), MemoryKind::Thought);
        assert_eq!(MemoryKind::from_str("THOUGHT"), MemoryKind::Thought);
        assert_eq!(MemoryKind::from_str("action"), MemoryKind::Action);
        assert_eq!(MemoryKind::from_str("Action"), MemoryKind::Action);
        assert_eq!(MemoryKind::from_str("message"), MemoryKind::Message);
        assert_eq!(MemoryKind::from_str("unknown"), MemoryKind::Message);
    }

    #[test]
    fn test_memory_kind_as_tag() {
        assert_eq!(MemoryKind::Thought.as_tag(), "thought");
        assert_eq!(MemoryKind::Action.as_tag(), "action");
        assert_eq!(MemoryKind::Message.as_tag(), "message");
    }

    #[test]
    fn test_with_id() {
        let fragment = MemoryFragmentBuilder::new("content".to_string(), MemoryKind::Message)
            .id(12345)
            .build();

        assert_eq!(fragment.id, 12345);
    }
}
