use super::types::{MemoryFragment, MemorySource};
use time::OffsetDateTime;

/// Builder for creating MemoryFragment instances with flexible configuration
pub struct MemoryFragmentBuilder {
    fragment: MemoryFragment,
}

impl MemoryFragmentBuilder {
    /// Create a new builder with required fields
    ///
    /// # Arguments
    /// * `content` - The memory content (required)
    /// * `source` - The memory source (required for tracking)
    pub fn new(content: String, source: MemorySource) -> Self {
        Self {
            fragment: MemoryFragment {
                id: 0, // Will be set by database when inserted
                content,
                timestamp: OffsetDateTime::now_utc(),
                source,
            },
        }
    }

    /// Set the id of the memory fragment
    ///
    /// Note: The id is typically auto-generated by the database.
    /// This method is particularly useful when constructing test data in unit tests.
    pub fn id(mut self, id: i64) -> Self {
        self.fragment.id = id;
        self
    }

    /// Set the content of the memory fragment
    pub fn content(mut self, content: String) -> Self {
        self.fragment.content = content;
        self
    }

    /// Set the timestamp
    pub fn timestamp(mut self, timestamp: OffsetDateTime) -> Self {
        self.fragment.timestamp = timestamp;
        self
    }

    /// Set the source of the memory fragment
    pub fn source(mut self, source: MemorySource) -> Self {
        self.fragment.source = source;
        self
    }

    /// Set source with API-specific defaults
    /// Handles the source mapping pattern used in HTTP handlers
    pub fn with_api_source(mut self, source: Option<String>) -> Self {
        self.fragment.source = if let Some(source_identifier) = source {
            let mut metadata = std::collections::HashMap::new();
            metadata.insert("type".to_string(), "api".to_string());

            MemorySource {
                channel: "information".to_string(),
                identifier: source_identifier,
                metadata,
            }
        } else {
            let mut metadata = std::collections::HashMap::new();
            metadata.insert("type".to_string(), "direct".to_string());

            MemorySource {
                channel: "information".to_string(),
                identifier: "api".to_string(),
                metadata,
            }
        };
        self
    }

    /// Build the final MemoryFragment
    pub fn build(self) -> MemoryFragment {
        self.fragment
    }
}

impl Default for MemoryFragmentBuilder {
    fn default() -> Self {
        let source = MemorySource {
            channel: "information".to_string(),
            identifier: "unknown".to_string(),
            metadata: [("type".to_string(), "unknown".to_string())]
                .into_iter()
                .collect(),
        };

        Self::new(String::new(), source)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::memory::types::MemorySource;

    #[test]
    fn test_builder_basic_functionality() {
        let source = MemorySource {
            channel: "information".to_string(),
            identifier: "test".to_string(),
            metadata: [("type".to_string(), "unit".to_string())]
                .into_iter()
                .collect(),
        };

        let fragment = MemoryFragmentBuilder::new("test content".to_string(), source).build();

        assert_eq!(fragment.content, "test content");
        assert_eq!(fragment.source.channel, "information");
    }

    #[test]
    fn test_memory_source_creation() {
        let dialogue_source = MemorySource {
            channel: "dialogue".to_string(),
            identifier: "alice".to_string(),
            metadata: [("type".to_string(), "input".to_string())]
                .into_iter()
                .collect(),
        };
        assert_eq!(dialogue_source.channel, "dialogue");
        assert_eq!(dialogue_source.identifier, "alice");
        assert_eq!(
            dialogue_source.metadata.get("type"),
            Some(&"input".to_string())
        );

        let info_source = MemorySource {
            channel: "information".to_string(),
            identifier: "config.json".to_string(),
            metadata: [("type".to_string(), "file".to_string())]
                .into_iter()
                .collect(),
        };
        assert_eq!(info_source.channel, "information");
        assert_eq!(info_source.identifier, "config.json");
        assert_eq!(info_source.metadata.get("type"), Some(&"file".to_string()));
    }

    #[test]
    fn test_memory_source_display() {
        let source = MemorySource {
            channel: "dialogue".to_string(),
            identifier: "bob".to_string(),
            metadata: [("type".to_string(), "input".to_string())]
                .into_iter()
                .collect(),
        };
        assert_eq!(format!("{}", source), "[dialogue:input] bob");

        let custom_source = MemorySource {
            channel: "information".to_string(),
            identifier: "example.com".to_string(),
            metadata: [("type".to_string(), "web".to_string())]
                .into_iter()
                .collect(),
        };
        assert_eq!(
            format!("{}", custom_source),
            "[information:web] example.com"
        );
    }

    #[test]
    fn test_with_api_source() {
        let source = MemorySource {
            channel: "information".to_string(),
            identifier: "unknown".to_string(),
            metadata: [("type".to_string(), "unknown".to_string())]
                .into_iter()
                .collect(),
        };

        let fragment = MemoryFragmentBuilder::new("test content".to_string(), source)
            .with_api_source(Some("test_source".to_string()))
            .build();

        assert_eq!(fragment.content, "test content");
        assert_eq!(fragment.source.channel, "information");
        assert_eq!(fragment.source.identifier, "test_source");
    }
}
