//! Convenience constructors for MemoryFragmentBuilder
//!
//! This module provides high-level convenience functions for creating MemoryFragmentBuilders
//! with common patterns used in the Ephemera AI application.

use epha_agent::publisher::PublisherMessage;
use loom_client::{MemoryFragmentBuilder, MemoryKind};
use serde_json::json;

/// Create a builder for a memory fragment from an AI thought with specified reasoning type
pub fn from_reasoning(content: String, reasoning_type: &str) -> MemoryFragmentBuilder {
    let content = json!({
        "type": reasoning_type,
        "thought": content,
    })
    .to_string();

    MemoryFragmentBuilder::new(content, MemoryKind::Thought)
}

/// Create a builder for a memory fragment from user dialogue input
pub fn from_dialogue_input(content: String, user: &str) -> MemoryFragmentBuilder {
    let content = json!({
        "type": "dialogue_input",
        "text": content,
        "participant": user,
    })
    .to_string();

    MemoryFragmentBuilder::new(content, MemoryKind::Event)
}

/// Create a builder for a memory fragment from dialogue response from AI
pub fn from_dialogue_response(content: String) -> MemoryFragmentBuilder {
    let content = json!({
        "type": "dialogue_output",
        "text": content,
        "participant": "self",
    })
    .to_string();

    MemoryFragmentBuilder::new(content, MemoryKind::Event)
}

/// Create a builder for a memory fragment from an information source
pub fn from_information(content: String, source: &str, source_type: &str) -> MemoryFragmentBuilder {
    let content = json!({
        "type": source_type,
        "text": content,
        "source": source,
    })
    .to_string();

    MemoryFragmentBuilder::new(content, MemoryKind::Event)
}

/// Create a builder for a memory fragment from an AI action
pub fn from_action(content: String, action_type: &str) -> MemoryFragmentBuilder {
    let content = json!({
        "type": action_type,
        "action": content,
    })
    .to_string();

    MemoryFragmentBuilder::new(content, MemoryKind::Action)
}

/// Create a builder for a memory fragment from a Producer event
///
/// Dual timestamp design:
/// - content.original_timestamp: When event was created (Producer-side)
/// - MemoryFragment.timestamp: When event entered context (epha-ai side, generated by .build())
pub fn from_producer_event(msg: PublisherMessage) -> MemoryFragmentBuilder {
    let content = json!({
        "type": "producer_event",
        "event_type": msg.message_type,
        "producer_id": msg.publisher_id,
        "payload": msg.payload,
        "original_timestamp": serde_json::to_string(&msg.timestamp).unwrap_or_else(|_| "\"unknown\"".to_string()),
        "priority": msg.priority.to_string(),
        "metadata": msg.metadata,
    })
    .to_string();

    MemoryFragmentBuilder::new(content, MemoryKind::Event)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_convenience_constructors() {
        let thought = from_reasoning("I need to analyze this".to_string(), "reasoning").build();
        assert!(thought.content.contains("\"thought\":\"I need to analyze this\""));
        assert!(thought.content.contains("\"type\":\"reasoning\""));
        assert_eq!(thought.kind, MemoryKind::Thought);

        let dialogue = from_dialogue_input("Hello world".to_string(), "alice").build();
        assert!(dialogue.content.contains("\"text\":\"Hello world\""));
        assert!(dialogue.content.contains("\"participant\":\"alice\""));
        assert_eq!(dialogue.kind, MemoryKind::Event);

        let response = from_dialogue_response("Hi there!".to_string()).build();
        assert!(response.content.contains("\"text\":\"Hi there!\""));
        assert!(response.content.contains("\"participant\":\"self\""));
        assert_eq!(response.kind, MemoryKind::Event);

        let info = from_information("Config loaded".to_string(), "config.json", "file").build();
        assert!(info.content.contains("\"text\":\"Config loaded\""));
        assert!(info.content.contains("\"source\":\"config.json\""));
        assert_eq!(info.kind, MemoryKind::Event);

        let action = from_action("Task completed".to_string(), "execution").build();
        assert!(action.content.contains("\"action\":\"Task completed\""));
        assert!(action.content.contains("\"type\":\"execution\""));
        assert_eq!(action.kind, MemoryKind::Action);
    }
}
